### ISSUE TITLE
1장 병목 코드 최적화 질문

### ISSUE THREAD

**Issue by teawon** [performance-lecture/lecture-1#11]
1. removeSpecialCharacter 함수 오타

```
// src/compoents/Article

function removeSpecialCharacter(str) {
  let _str = str.substring(0, 300);
  _str = str.replace(/[#_*~&;![\]`>\n=\->]/g, "");   //   _str = _str.replace(/[#_*~&;![\]`>\n=\->]/g, "");   // 
  return _str;
}

```

300자로 잘랐던 변수를 활용해야하므로 str.replace -> _str.replace 부분으로 변수 오타를 수정해야할 것 같습니다!

2. ArticleList항목의 시간차이

35P의 교재에서는 ArticleList에 대해 1.4s가 나왔지만 제 로컬에서 돌렸을때에는 242ms정도 밖에 나오지 않았습니다.

로컬환경에 따라 이렇게 시간차이가 클 수가 있나요?

시간차이가 크지 않아서 책 내용을 보지 않았더라면 병목현상임을 확인하지 못했을 것 같은데 병목확인을 위해 의도적으로 컴퓨터  사양을 낮추고 테스트를 돌리는 경우도 있는지 궁금합니다

![image](https://github.com/performance-lecture/lecture-1/assets/78795820/afc53720-8bf0-438c-aced-887397c0cbe8)

**Comment by hackurity01** [comment]
1. 오타 제보 감사합니다! 
2. 네 있습니다. 책 75-76쪽을 보면 Performance 패널에서 CPU 성능을 제한하는 옵션에 대해서 설명하고 있습니다.
<img width="964" alt="image" src="https://github.com/performance-lecture/lecture-1/assets/8624075/b7e153f0-3d54-4737-8f50-cdb5f1ff3419">
