### ISSUE TITLE
프로젝트가 실행이 되지 않습니다.

### ISSUE THREAD

**Issue by merrybmc** [performance-lecture/lecture-1#12]
프론트엔드 성능 최적화 가이드 책 독자입니다.

프로젝트를 clone하고 install, start, server, serve를 다 해보았는데

localhost:3000에서 사이트에 연결할 수 없는 페이지라고 계속 뜹니다 ㅜㅜ

혹시 저와 같은 현상을 겪으신 분이 계시거나 해결 방법을 아시는 분이 계실까요?? 공부하고 싶습니다.

![image](https://github.com/performance-lecture/lecture-1/assets/65064563/e04bff11-2780-4b5a-a132-5a336c685b09)

![image](https://github.com/performance-lecture/lecture-1/assets/65064563/df34f2ef-0321-454c-8b87-158eb593400d)

**Comment by hackurity01** [comment]
안녕하세요 @merrybmc 님,
node 18버전의 호환 문제로 보입니다.
node 16버전으로 다시 해보시겠어요?
(참고: https://www.inflearn.com/questions/735601/node-version%EC%9C%BC%EB%A1%9C-%EC%9D%B8%ED%95%9C-%EC%98%A4%EB%A5%98)

**Comment by merrybmc** [comment]
> 안녕하세요 @merrybmc 님, node 18버전의 호환 문제로 보입니다. node 16버전으로 다시 해보시겠어요? (참고: https://www.inflearn.com/questions/735601/node-version%EC%9C%BC%EB%A1%9C-%EC%9D%B8%ED%95%9C-%EC%98%A4%EB%A5%98)

감사합니다! 해결되었습니다. :)
