### ISSUE TITLE
http://localhost:3000 실행안됨

### ISSUE THREAD

**Issue by 5647kr** [performance-lecture/lecture-1#13]
사이트에 연결할 수 없다고 뜹니다 확인 부탁드립니다

**Comment by hackurity01** [comment]
안녕하세요, @5647kr 님.

어느 부분에서 어떤 에러가 발생했는지, 실행할 때는 어떻게 실행했는지 등
문제를 파악할 수 있는 정보를 함께 알려주시면 더 좋을 것 같습니다.

만약 npm run start 과정에서 `Error: error:0308010C:digital envelope routines::unsupported` 이런 에러가 발생한 거라면,
아래 이슈 확인해보시길 바랍니다.
https://github.com/performance-lecture/lecture-1/issues/12

**Comment by 5647kr** [comment]
19버전인데도 호환이 안되네요 16으로 낮춰서 진행하겠습니다 감사합니다
