### ISSUE TITLE
Experience Scripting이 무엇인가요?

### ISSUE THREAD

**Issue by imhjnoh** [performance-lecture/lecture-1#15]
안녕하세요 선생님, 좋은 책 써주셔서 감사합니다.
책으로 스터디 중에 질문이 생겨 이슈를 통해 남깁니다.
32페이지 Event Log 탭에서 Experience Scripting을 확인할 수 있다고 말씀주셨는데, 처음 보는 용어라 검색해보았으나 마땅한 검색 결과가 없었습니다.
Experience Scripting이 무엇을 의미하는 단어인지 궁금합니다.
아니면 관련 정보를 찾아볼 수 있는 방법을 알려주시면 매우 감사드리겠습니다..!!

**Comment by hackurity01** [comment]
안녕하세요
말씀하신 부분 확인해봤는데요, 아무래도 해당 부분을 작성할 때 잘못 작성한 것 같습니다...
(잘은 모르깄지만, 뭔가 자동입력되어 버렸거나 다른 표현을 쓰다가 미처 문구를 정리하지 못했던 것 같네요..)

해당 Experience Scripting이 아니라 그냥 Scripting으로 봐주시면 될 것 같습니다.

혼란을 드려서 죄송합니다 ㅠ
또 제보해주셔서,그리고 책에 관심을 거져주셔서 감사합니다!

**Comment by imhjnoh** [comment]
빠른 답변 감사드립니다! 덕분에 재밌게 공부하고 있습니다.
좋은 하루 되세요~😊
