### ISSUE TITLE
1장. 텍스트 압축 적용 질문

### ISSUE THREAD

**Issue by rkdcodus** [performance-lecture/lecture-1#16]
안녕하세요! 
덕분에 책으로 같이 실습하며 많이 배우고 있습니다! 
1장에 텍스트 압축 따라하면서 궁금한 점이 있어 이슈 남깁니다😊

텍스트 압축 적용을 위해 serve 라이브러리 명령어에서 `-u` 옵션 제거 후 다시 실행했는데요

![image](https://github.com/user-attachments/assets/b977ec4f-4ccc-4fbb-b1a5-089378aba53b)

명령어가 실행되면서 나타난 `File sizes after gzip` 목록을 보고
네트워크 응답 헤더에서 `Content-encoding` 이 있는지 확인했을 때 
어떤 건  `Content-encoding: gzip`이 있고 어떤건 없습니다.

![image](https://github.com/user-attachments/assets/c8fe9f83-07a7-4de6-88ee-8f8039d340f9)
이 4가지 파일이 안보이는데 왜 보이지 않는지 이유가 궁금합니다. 
텍스트 압축이 제대로 되지 않은 걸까요? 
아니면 제가 어딜 놓친걸까요!?

<br>

ex) main.d5fdc538.chunk.js 
![image](https://github.com/user-attachments/assets/ea12ecb8-55e3-41ee-aa68-59b52dc28861)

**Comment by hackurity01** [comment]
안녕하세요, @rkdcodus 님.

gzip의 압축 효율은 리소스의 사이즈가 너무 작으면 거의 압축되지 않거나 압축을 처리하는 리소스 대비 그 효과가 미비합니다.
그 기준은 5kb 정도로 5kb 이하의 리소스이면 그 효율이 크지 않습니다. (경우에 따라서는 1~2kb로 얘기하기도 하지만, 암튼 그 쯤)
따라서 일반적인 gzip 압축 로직에서 기준 사이즈 이하이면 압축하지 않는 로직이 들어가 있습니다.

serve 코드를 살펴보면 압축 라이브러리로 expressjs의 compression 라이브러리를 사용하고 있고,
compression 라이브러리에서는 아래와 같이 threshold를 기본값으로 1024(아마 byte)로 설정해두고 그 이하이면 압축하지 않고 있습니다.
<img width="388" alt="image" src="https://github.com/user-attachments/assets/9e01bb64-f636-40d8-aea6-0bd13b6aed58">
<img width="708" alt="image" src="https://github.com/user-attachments/assets/6b3defa4-12ae-4ad4-8e17-2b1d432f3460">
https://github.com/expressjs/compression/blob/master/index.js#L157

말씀하신 파일들의 사이즈를 보면 1KB(1024Byte)를 넘지 않습니다.
따라서 threshold를 넘지 않아 압축하지 않은 것으로 보입니다.

답변이 도움되셨길 바라며, 책에 관심을 가져주셔서 감사합니다! 😄
