### ISSUE TITLE
병목코드 최적화

### ISSUE THREAD

**Issue by pgg-dev** [performance-lecture/lecture-1#9]
교재 26p diagnostics 섹션의 'Reduce JavaScript execution time' 항목에 관련된 내용이 있는데
코드를 실행시켜 검사해보면 교재와 내용이 다른데요..!  다른 이유가 무엇인가요?

**Comment by hackurity01** [comment]
안녕하세요 pgg-dev님

어떻게 다른 건지 보여주실 수 있나요?
코드 실행 환경과 크롬 버전에 따라서 달라질 수는 있습니다.
